Mountain.create(name: "Marcy", elevation: 5344)
Mountain.create(name: "Algonquin", elevation: 5144)
Mountain.create(name: "Haystack", elevation: 4960)
Mountain.create(name: "Skylight", elevation: 4926)
Mountain.create(name: "Whiteface", elevation: 4867)
Mountain.create(name: "Dix", elevation: 4857)
Mountain.create(name: "Gray", elevation: 4840)
Mountain.create(name: "Iroquois Peak", elevation: 4840)
Mountain.create(name: "Basin", elevation: 4827)
Mountain.create(name: "Gothics", elevation: 4736)
Mountain.create(name: "Colden", elevation: 4714)
Mountain.create(name: "Giant", elevation: 4627)
Mountain.create(name: "Nippletop", elevation: 4620)
Mountain.create(name: "Santanoni", elevation: 4607)
Mountain.create(name: "Redfield", elevation: 4606)
Mountain.create(name: "Wright Peak", elevation: 4580)
Mountain.create(name: "Saddleback", elevation: 4515)
Mountain.create(name: "Panther", elevation: 4442)
Mountain.create(name: "TableTop", elevation: 4427)
Mountain.create(name: "Rocky Peak", elevation: 4420)
Mountain.create(name: "Macomb", elevation: 4405)
Mountain.create(name: "Armstrong", elevation: 4400)
Mountain.create(name: "Hough", elevation: 4400)
Mountain.create(name: "Seward", elevation: 4361)
Mountain.create(name: "Marshall", elevation: 4360)
Mountain.create(name: "Allen", elevation: 4340)
Mountain.create(name: "Big Slide", elevation: 4240)
Mountain.create(name: "Esther", elevation: 4240)
Mountain.create(name: "Upper Wolfjaw", elevation: 4185)
Mountain.create(name: "Lower Wolfjaw", elevation: 4175)
Mountain.create(name: "Street", elevation: 4166)
Mountain.create(name: "Phelps", elevation: 4161)
Mountain.create(name: "Donaldson", elevation: 4140)
Mountain.create(name: "Seymour", elevation: 4120)
Mountain.create(name: "Sawteeth", elevation: 4100)
Mountain.create(name: "Cascade", elevation: 4098)
Mountain.create(name: "South Dix", elevation: 4060)
Mountain.create(name: "Porter", elevation: 4059)
Mountain.create(name: "Colvin", elevation: 4057)
Mountain.create(name: "Emmons", elevation: 4040)
Mountain.create(name: "Dial", elevation: 4020)
Mountain.create(name: "Grace Peak", elevation: 4012)
Mountain.create(name: "Blake Peak", elevation: 3960)
Mountain.create(name: "Cliff", elevation: 3960)
Mountain.create(name: "Nye", elevation: 3895)
Mountain.create(name: "Couchsachraga", elevation: 3820)
